const express = require('express')
const app = express()
const PORT = process.env.PORT || 8080;
const path = require('path')


const { _file } = require('./business/files/file')
const { DIR_URL } = require('./business/assets')


var init = async () => {
    //steps to convert files and generate manifests
    //1. list of all files.
    //2. compress all files using ffmpeg. If a file is already compressed do not compress it agin.
    //3. generate manifest. it will gerneate .mpd + .mp4 files.
    //4. delete compressed files generated by ffmpg.


    //implementation of the above steps--
    //1. list of all files.
    const _list = await _file.readDir(DIR_URL);
    console.log(_list)

    //2. compress all files using ffmpeg. If a file is already compressed do not compress it agin.
    

    
    
}

init()






app.listen(PORT, _ => {
    console.log(`App listening on port http://localhost:${PORT}`);
    console.log('Press Ctrl+C to quit.');
  });